### ISSUE TITLE
request with error

### ISSUE THREAD

**Issue by aliuncoBamilo** [scarabresearch/EmarsysPredictSDKiOS#4]
how can I find it out that my recommendation request had any errors or not?

```swift
let recommendReq = EMRecommendationRequest(logic: "\(recommendationLogic)")
     recommendReq.limit = LIMITATION
     recommendReq.completionHandler = { receivedRecs in
             processRecommandationResult(result: receivedRecs)
      }
```
the code above defines the completion handler for request, but if the request has any errors, this function will not be fired!

**Comment by mrcompoteee** [comment]
@aliuncoBamilo usually I use EMRecommendationRequest together with EMTransaction. And to send a transaction you're probably going to use 'send' function, which accepts errorHandler block as a parameter. Here is an example:

```Swift
let transaction = EMTransaction()
let request = EMRecommendationRequest(logic: "CART")
request.completionHandler = { result in
      //
}
            
transaction.recommend(request)
            
EMSession.shared().send(transaction, errorHandler: { error in
      //
})
```

**Comment by andrascsibi** [comment]
@mrcompoteee thanks for the answer, I hope this helps @aliuncoBamilo . I'm closing this issue for now.
