### ISSUE TITLE
Ampersand characters (&) are not URL encoded

### ISSUE THREAD

**Issue by andrascsibi** [scarabresearch/EmarsysPredictSDKiOS#5]
One of our dear client reports.

> Some of our categories have a "&" sign in it. Which is correct and for a reason e.g. "Musik, Filme & Bücher". If the app sends a category event with value "Musik, Filme & Bücher" the request fails. Because the `&` is not encoded so it will destroy the query string of the request, as it is recognized as a seperator of parameters within the request.
> And this is exactly the bug: `&` within the name of categories is not encoded correctly by the SDK and this is why it seems to be failing.

The problem might be that the standard library doesn't do proper URL encoding. https://stackoverflow.com/questions/8088473/how-do-i-url-encode-a-string

**Comment by Hozeee** [comment]
We've fixed this issue, please check this commit: https://github.com/scarabresearch/EmarsysPredictSDKiOS/commit/d52e7042076a62764f1b4bae75a1413b9b905f1b
